import AweiKA19 from '/products/awei/Awei KA 19.jpg';
import AweiKA5 from '/products/awei/Awei KA5.jpg';
import AweiKA8 from '/products/awei/Awei KA8.jpg';
import AweiY200HIFI from '/products/awei/Awei Y 200 HIFI Bluetooth Speaker.jpg';
import AweiY669 from '/products/awei/Awei Y 669.jpg';
import AweiY900MiniBluetoothSpeaker from '/products/awei/Awei Y 900 Mini Bluetooth Speaker.jpg';
import AweiY370 from '/products/awei/Awei Y370.png';
import AweiY885 from '/products/awei/Awei Y885.jpg';

export const aweiProducts = [
  {
    id: 32,
    Name: 'KA 19',
    pic: AweiKA19,
    category: 'Earphones',
    Price: 25,
    subTitle: '6 months warranty',
    discount: 5,
    O_price: 30,
    clicked: false,
    brand: 'Awei',
  },
  {
    id: 33,
    Name: 'KA5',
    pic: AweiKA5,
    category: 'Earphones',
    Price: 35,
    subTitle: '6 months warranty',
    discount: 10,
    O_price: 40,
    clicked: false,
    brand: 'Awei',
  },
  {
    id: 34,
    Name: 'KA8',
    pic: AweiKA8,
    category: 'Earphones',
    Price: 40,
    subTitle: '6 months warranty',
    discount: 5,
    O_price: 45,
    clicked: false,
    brand: 'Awei',
  },
  {
    id: 35,
    Name: 'Y200 HIFI',
    pic: AweiY200HIFI,
    category: 'Speaker',
    Price: 60,
    subTitle: '6 months warranty',
    discount: 10,
    O_price: 70,
    clicked: false,
    brand: 'Awei',
  },
  {
    id: 36,
    Name: 'Y669',
    pic: AweiY669,
    category: 'Speaker',
    Price: 55,
    subTitle: '6 months warranty',
    discount: 5,
    O_price: 60,
    clicked: false,
    brand: 'Awei',
  },
  {
    id: 37,
    Name: 'Y900 Mini',
    pic: AweiY900MiniBluetoothSpeaker,
    category: 'Speaker',
    Price: 35,
    subTitle: '6 months warranty',
    discount: 5,
    O_price: 40,
    clicked: false,
    brand: 'Awei',
  },
  {
    id: 38,
    Name: 'Y370',
    pic: AweiY370,
    category: 'Speaker',
    Price: 70,
    subTitle: '6 months warranty',
    discount: 10,
    O_price: 80,
    clicked: false,
    brand: 'Awei',
  },
  {
    id: 39,
    Name: 'Y885',
    pic: AweiY885,
    category: 'Speaker',
    Price: 50,
    subTitle: '6 months warranty',
    discount: 8,
    O_price: 58,
    clicked: false,
    brand: 'Awei',
  },
];
