import CozydotsTS01 from '/products/joyroom/Cozydots TS01.jpg';
import JRBB1TWS from '/products/joyroom/JR BB 1 TWS.png';
import JRBC1ANC from '/products/joyroom/JR BC1 ANC.png';
import JRFC1 from '/products/joyroom/JR FC 1.png';
import JRFC2White from '/products/joyroom/JR FC 2 White.jpg';
import JRFC2Black from '/products/joyroom/JR FC 2 Black.jpg';
import JRFN2ANCBlack from '/products/joyroom/JR FN2 ANC Black.jpg';
import JRFN2ANC from '/products/joyroom/JR FN2 ANC.jpg';
import JRFT1Pro from '/products/joyroom/JR FT 1 Pro.jpg';
import JRFT3 from '/products/joyroom/JR FT 3.jpg';
import JRFT3Pro from '/products/joyroom/JR FT 3 Pro.jpg';
import JRFT5 from '/products/joyroom/JR FT 5.jpg';
import JRFunpodsFB2 from '/products/joyroom/JR Funpods FB 2.png';
import JRFunpodsFB3 from '/products/joyroom/JR Funpods FB3.png';
import JRFunpodsFb1 from '/products/joyroom/JR Funpods Fb1.jpg';
import JRT03sProANC from '/products/joyroom/JR T03s Pro ANC.jpg';
import JRT03sProMax from '/products/joyroom/JR T03s Pro Max.jpg';
import JRT03sProPlus from '/products/joyroom/JR T03s Pro+.jpg';
import OpenfreeOE1 from '/products/joyroom/Openfree OE1.jpg';
import RemaxWatch9 from '/products/joyroom/Remax Watch 9.jpg';

export const joyRoomProducts = [
  {
    id: 23,
    Name: 'Cozydots TS01',
    pic: CozydotsTS01,
    category: 'Earphones',
    Price: 20,
    subTitle: '3 months warranty',
    discount: 5,
    O_price: 25,
    clicked: false,
  },
  {
    id: 24,
    Name: 'JR BB 1 TWS',
    pic: JRBB1TWS,
    category: 'Earbuds',
    Price: 18,
    subTitle: '3 months warranty',
    discount: 10,
    O_price: 20,
    clicked: false,
  },
  {
    id: 25,
    Name: 'JR BC1 ANC',
    pic: JRBC1ANC,
    category: 'Earphones',
    Price: 40,
    subTitle: '2 years warranty',
    discount: 8,
    O_price: 45,
    clicked: false,
  },
  {
    id: 26,
    Name: 'JR FC 1',
    pic: JRFC1,
    category: 'Earbuds',
    Price: 22,
    subTitle: '3 months warranty',
    discount: 5,
    O_price: 25,
    clicked: false,
  },
  {
    id: 27,
    Name: 'JR FC 2 White',
    pic: JRFC2White,
    category: 'Earbuds',
    Price: 30,
    subTitle: '3 months warranty',
    discount: 7,
    O_price: 35,
    clicked: false,
  },
  {
    id: 28,
    Name: 'JR FC 2 Black',
    pic: JRFC2Black,
    category: 'Earbuds',
    Price: 30,
    subTitle: '3 months warranty',
    discount: 7,
    O_price: 35,
    clicked: false,
  },
  {
    id: 29,
    Name: 'JR FN2 ANC Black',
    pic: JRFN2ANCBlack,
    category: 'Earbuds',
    Price: 50,
    subTitle: '2 years warranty',
    discount: 12,
    O_price: 55,
    clicked: false,
  },
  {
    id: 30,
    Name: 'JR FN2 ANC',
    pic: JRFN2ANC,
    category: 'Earbuds',
    Price: 50,
    subTitle: '2 years warranty',
    discount: 12,
    O_price: 55,
    clicked: false,
  },
  {
    id: 31,
    Name: 'JR FT 1 Pro',
    pic: JRFT1Pro,
    category: 'Earphones',
    Price: 32,
    subTitle: '3 months warranty',
    discount: 5,
    O_price: 35,
    clicked: false,
  },
  {
    id: 32,
    Name: 'JR FT 3',
    pic: JRFT3,
    category: 'Earphones',
    Price: 25,
    subTitle: '3 months warranty',
    discount: 5,
    O_price: 30,
    clicked: false,
  },
  {
    id: 33,
    Name: 'JR FT 3 Pro',
    pic: JRFT3Pro,
    category: 'Earphones',
    Price: 30,
    subTitle: '3 months warranty',
    discount: 5,
    O_price: 35,
    clicked: false,
  },
  {
    id: 34,
    Name: 'JR FT 5',
    pic: JRFT5,
    category: 'Earphones',
    Price: 40,
    subTitle: '2 years warranty',
    discount: 10,
    O_price: 45,
    clicked: false,
  },
  {
    id: 35,
    Name: 'JR Funpods FB 2',
    pic: JRFunpodsFB2,
    category: 'Earbuds',
    Price: 20,
    subTitle: '3 months warranty',
    discount: 5,
    O_price: 25,
    clicked: false,
  },
  {
    id: 36,
    Name: 'JR Funpods FB 3',
    pic: JRFunpodsFB3,
    category: 'Earbuds',
    Price: 25,
    subTitle: '3 months warranty',
    discount: 5,
    O_price: 30,
    clicked: false,
  },
  {
    id: 37,
    Name: 'JR Funpods Fb1',
    pic: JRFunpodsFb1,
    category: 'Earbuds',
    Price: 18,
    subTitle: '3 months warranty',
    discount: 5,
    O_price: 20,
    clicked: false,
  },
  {
    id: 38,
    Name: 'JR T03s Pro ANC',
    pic: JRT03sProANC,
    category: 'Earbuds',
    Price: 60,
    subTitle: '2 years warranty',
    discount: 12,
    O_price: 65,
    clicked: false,
  },
  {
    id: 39,
    Name: 'JR T03s Pro Max',
    pic: JRT03sProMax,
    category: 'Earbuds',
    Price: 70,
    subTitle: '2 years warranty',
    discount: 15,
    O_price: 80,
    clicked: false,
  },
  {
    id: 40,
    Name: 'JR T03s Pro+',
    pic: JRT03sProPlus,
    category: 'Earbuds',
    Price: 65,
    subTitle: '2 years warranty',
    discount: 10,
    O_price: 70,
    clicked: false,
  },
  {
    id: 41,
    Name: 'Openfree OE1',
    pic: OpenfreeOE1,
    category: 'Earphones',
    Price: 35,
    subTitle: '3 months warranty',
    discount: 8,
    O_price: 40,
    clicked: false,
  },
  {
    id: 42,
    Name: 'Remax Watch 9',
    pic: RemaxWatch9,
    category: 'Watch',
    Price: 55,
    subTitle: '3 months warranty',
    discount: 10,
    O_price: 60,
    clicked: false,
  },
];
