import OraimoConch2Earphones from '/products/oraimo/Oraimo Conch 2 Earphones.jpg';
import OraimoNecklace4Neckband from '/products/oraimo/Oraimo Nrcklace 4 Neckband.jpg';
import OraimoFreepods3C from '/products/oraimo/Oraimo Freepods 3C.jpg';
import OraimoRoverRGBPortableBluetoothSpeaker from '/products/oraimo/Oraimo Rover RGB Portable Bluetooth Speaker.jpg';
import OraimoFreepods4ANC from '/products/oraimo/Oraimo Freepods 4 ANC.jpg';
import OraimoShark4Neckband from '/products/oraimo/Oraimo Shark 4 Neckband.jpg';
import OraimoFreepodsLiteBlack from '/products/oraimo/Oraimo Freepods Lite - Black.png';
import OraimoSpacebudsHybridANC from '/products/oraimo/Oraimo Spacebuds Hybrid ANC TWS.jpg';
import OraimoFreepodsLiteLakeBlue from '/products/oraimo/Oraimo Freepods Lite - Lake Blue.png';
import OraimoFreepodsLiteNebulaBlue from '/products/oraimo/Oraimo Freepods Lite - Nebula Blue.png';
import OraimoTrumpet3Earphones from '/products/oraimo/Oraimo Trumpet 3 Earphones.jpg';
import OraimoWatch2R from '/products/oraimo/Oraimo Watch 2R.jpg';
import OraimoWatch4Plus from '/products/oraimo/Oraimo Watch 4 Plus.jpg';
import OraimoFreepodsProPlus from '/products/oraimo/Oraimo Freepods Pro+.jpg';
import OraimoHALO2SEarphones from '/products/oraimo/Oraimo HALO 2S Earphones.jpg';
import OraimoWatchER from '/products/oraimo/Oraimo Watch ER.jpg';
import OraimoHALO4Earphones from '/products/oraimo/Oraimo HALO 4 Earphones.jpg';
import OraimoWatchES from '/products/oraimo/Oraimo Watch ES.jpg';
import OraimoHaloAiryEarphones from '/products/oraimo/Oraimo Halo Airy Earphones.png';
import OraimoNecklaceLite from '/products/oraimo/Oraimo Necklace Lite.jpg';
import OraimoNecklaceProNeckband from '/products/oraimo/Oraimo Necklace Pro Neckband.png';
import OraimoWatchLite from '/products/oraimo/Oraimo Watch Lite.jpg';
import OraimoWrapPortableSpeaker from '/products/oraimo/Oraimo Wrap Portable Speaker.jpg';
import OraimoBoomPortableWirelessSpeaker from '/products/oraimo/Oraimo Boom Portable Wireless Speaker.jpg';
import OraimoBoompop2ENC from '/products/oraimo/Oraimo Boompop 2 ENC.jpg';
import OraimoSliceLinkPro from '/products/oraimo/Oraimo Slice Link Pro.jpg';
import OraimoSliceLink from '/products/oraimo/Oraimo Slice Link.jpg';
import OraimoToast15Flash from '/products/oraimo/Oraimo Toast 15 Flash.jpg';
import OraimoTraveler15Flash from '/products/oraimo/Oraimo Traveler 15 Flash.jpg';
import OraimoTraveler22_5PD from '/products/oraimo/Oraimo Traveler 22.5 PD.jpg';
import OraimoTraveler3Lit from '/products/oraimo/Oraimo Traveler 3 Lit.jpg';

export const oraimoProducts = [
  {
    id: 0,
    Name: 'Conch 2',
    pic: OraimoConch2Earphones,
    category: 'Earphones',
    Price: 10,
    subTitle: '6 months warranty',
    discount: 10,
    O_price: 12,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 1,
    Name: 'Necklace 4',
    pic: OraimoNecklace4Neckband,
    category: 'Neckband',
    Price: 15,
    subTitle: '1 year warranty',
    discount: 15,
    O_price: 18,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 2,
    Name: 'Freepods 3C',
    pic: OraimoFreepods3C,
    category: 'Earbuds',
    Price: 25,
    subTitle: '1 year warranty',
    discount: 20,
    O_price: 30,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 3,
    Name: 'Rover RGB',
    pic: OraimoRoverRGBPortableBluetoothSpeaker,
    category: 'Speaker',
    Price: 35,
    subTitle: '1 years warranty',
    discount: 10,
    O_price: 40,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 4,
    Name: 'Freepods 4 ANC',
    pic: OraimoFreepods4ANC,
    category: 'Earbuds',
    Price: 40,
    subTitle: '1 year warranty',
    discount: 15,
    O_price: 47,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 5,
    Name: 'Shark 4 Neckband',
    pic: OraimoShark4Neckband,
    category: 'Neckband',
    Price: 20,
    subTitle: '6 months warranty',
    discount: 5,
    O_price: 22,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 6,
    Name: 'Freepods Lite',
    pic: OraimoFreepodsLiteBlack,
    category: 'Earbuds',
    Price: 18,
    subTitle: '1 year warranty',
    discount: 10,
    O_price: 20,
    clicked: false,
    brand: 'Oraimo',
    color: 'Black',
  },
  {
    id: 7,
    Name: 'Hybrid ANC TWS',
    pic: OraimoSpacebudsHybridANC,
    category: 'Earbuds',
    Price: 50,
    subTitle: '1 year warranty',
    discount: 10,
    O_price: 55,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 8,
    Name: 'Freepods Lite',
    pic: OraimoFreepodsLiteLakeBlue,
    category: 'Earbuds',
    Price: 18,
    subTitle: '1 year warranty',
    discount: 10,
    O_price: 20,
    clicked: false,
    brand: 'Oraimo',
    color: 'Lake Blue',
  },
  {
    id: 9,
    Name: 'Freepods Lite',
    pic: OraimoFreepodsLiteNebulaBlue,
    category: 'Earbuds',
    Price: 18,
    subTitle: '1 year warranty',
    discount: 10,
    O_price: 20,
    clicked: false,
    brand: 'Oraimo',
    color: 'Nebula Blue',
  },
  {
    id: 10,
    Name: 'Trumpet 3',
    pic: OraimoTrumpet3Earphones,
    category: 'Earphones',
    Price: 12,
    subTitle: '6 months warranty',
    discount: 8,
    O_price: 14,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 11,
    Name: 'Watch 2R',
    pic: OraimoWatch2R,
    category: 'Watch',
    Price: 60,
    subTitle: '1 years warranty',
    discount: 15,
    O_price: 70,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 12,
    Name: 'Watch 4 Plus',
    pic: OraimoWatch4Plus,
    category: 'Watch',
    Price: 75,
    subTitle: '1 years warranty',
    discount: 20,
    O_price: 90,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 13,
    Name: 'Freepods Pro+',
    pic: OraimoFreepodsProPlus,
    category: 'Earbuds',
    Price: 45,
    subTitle: '1 year warranty',
    discount: 10,
    O_price: 50,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 14,
    Name: 'HALO 2S',
    pic: OraimoHALO2SEarphones,
    category: 'Earphones',
    Price: 10,
    subTitle: '6 months warranty',
    discount: 10,
    O_price: 12,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 15,
    Name: 'Watch ER',
    pic: OraimoWatchER,
    category: 'Watch',
    Price: 65,
    subTitle: '1 years warranty',
    discount: 15,
    O_price: 75,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 16,
    Name: 'HALO 4',
    pic: OraimoHALO4Earphones,
    category: 'Earphones',
    Price: 15,
    subTitle: '6 months warranty',
    discount: 10,
    O_price: 17,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 17,
    Name: 'Watch ES',
    pic: OraimoWatchES,
    category: 'Watch',
    Price: 70,
    subTitle: '1 years warranty',
    discount: 20,
    O_price: 85,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 18,
    Name: 'Halo Airy',
    pic: OraimoHaloAiryEarphones,
    category: 'Earphones',
    Price: 15,
    subTitle: '6 months warranty',
    discount: 10,
    O_price: 17,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 19,
    Name: 'Necklace Lite',
    pic: OraimoNecklaceLite,
    category: 'Neckband',
    Price: 12,
    subTitle: '6 months warranty',
    discount: 5,
    O_price: 14,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 20,
    Name: 'Necklace Pro',
    pic: OraimoNecklaceProNeckband,
    category: 'Neckband',
    Price: 25,
    subTitle: '1 year warranty',
    discount: 10,
    O_price: 28,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 21,
    Name: 'Watch Lite',
    pic: OraimoWatchLite,
    category: 'Watch',
    Price: 40,
    subTitle: '1 years warranty',
    discount: 10,
    O_price: 45,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 22,
    Name: 'Wrap Portable',
    pic: OraimoWrapPortableSpeaker,
    category: 'Speaker',
    Price: 30,
    subTitle: '1 years warranty',
    discount: 10,
    O_price: 35,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 23,
    Name: 'Boom Portable',
    pic: OraimoBoomPortableWirelessSpeaker,
    category: 'Speaker',
    Price: 50,
    subTitle: '1 year warranty',
    discount: 5,
    O_price: 55,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 24,
    Name: 'Boompop 2 ENC',
    pic: OraimoBoompop2ENC,
    category: 'Earbuds',
    Price: 60,
    subTitle: '1 year warranty',
    discount: 8,
    O_price: 65,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 25,
    Name: 'Slice Link Pro',
    pic: OraimoSliceLinkPro,
    category: 'Power Bank',
    Price: 40,
    subTitle: '1 year warranty',
    discount: 5,
    O_price: 45,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 26,
    Name: 'Slice Link',
    pic: OraimoSliceLink,
    category: 'Power Bank',
    Price: 35,
    subTitle: '1 year warranty',
    discount: 10,
    O_price: 40,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 27,
    Name: 'Toast 15 Flash',
    pic: OraimoToast15Flash,
    category: 'Power Bank',
    Price: 45,
    subTitle: '2 years warranty',
    discount: 10,
    O_price: 50,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 28,
    Name: 'Traveler 15 Flash',
    pic: OraimoTraveler15Flash,
    category: 'Power Bank',
    Price: 55,
    subTitle: '2 years warranty',
    discount: 5,
    O_price: 60,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 29,
    Name: 'Traveler 22.5 PD',
    pic: OraimoTraveler22_5PD,
    category: 'Power Bank',
    Price: 65,
    subTitle: '2 years warranty',
    discount: 8,
    O_price: 70,
    clicked: false,
    brand: 'Oraimo',
  },
  {
    id: 30,
    Name: 'Traveler 3 Lit',
    pic: OraimoTraveler3Lit,
    category: 'Power Bank',
    Price: 25,
    subTitle: '1 year warranty',
    discount: 5,
    O_price: 30,
    clicked: false,
    brand: 'Oraimo',
  },
];
